### ISSUE TITLE
Wrong arguments parse

### ISSUE THREAD

**Issue by ghost** [erikringsmuth/requirejs-router#2]
If you use argument with upcoming zeros, e.g.: #/trips/cancel/0001
000 disappears, the argument is 1

Seems because of 
 else if (!isNaN(value) && value !== '') {
          // numeric
          args[arg] = +value;
        }

BTW cool router, thanx

**Comment by erikringsmuth** [comment]
Good catch! I added an additional check so that any value starting with a zero won't be considered a number. It will be left as a string.

**Comment by ghost** [comment]
Cool, thanx!
